apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    used-by: {{ template "fullname" . }}-nginx
data:
  nginx.conf: |

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;

            root /usr/share/nginx/html;
            index index.html index.htm;
            server_name {{ .Values.ingress.host }};

            location / {
              proxy_set_header X-Forwarded-For $remote_addr;
              {{- if .Values.ingress.ssl.enabled }}
                proxy_set_header X-Forwarded-Proto https;
              {{- else }}
                proxy_set_header X-Forwarded-Proto http;
              {{- end }}
              proxy_set_header Host $http_host;

              proxy_pass http://127.0.0.1:8000;
              proxy_redirect off;
              proxy_http_version 1.1;
              proxy_buffering off;

              chunked_transfer_encoding off;
            }

            location ~* /ws {
              proxy_pass http://127.0.0.1:8000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_read_timeout 86400;
              proxy_set_header X-Forwarded-For $remote_addr;
              {{- if .Values.ingress.ssl.enabled }}
                proxy_set_header X-Forwarded-Proto https;
              {{- else }}
                proxy_set_header X-Forwarded-Proto http;
              {{- end }}
              proxy_set_header Host $http_host;
          }
      }



